{
  "config": {
    "step": {
      "user": {
        "data": {
          "host": "[%key:common::config_flow::data::host%]",
          "password": "[%key:common::config_flow::data::password%]"
        }
      },
      "reauth_confirm": {
        "data": {
          "host": "[%key:common::config_flow::data::host%]",
          "password": "[%key:common::config_flow::data::password%]"
        },
        "description": "Reauthenticate"
      }
    },
    "error": {
      "cannot_connect": "[%key:common::config_flow::error::cannot_connect%]",
      "invalid_auth": "[%key:common::config_flow::error::invalid_auth%]",
      "unknown": "[%key:common::config_flow::error::unknown%]"
    },
    "abort": {
      "already_configured": "[%key:common::config_flow::abort::already_configured_device%]",
      "reauth_successful": "Reauthentication was successful"
    }
  },
  "options": {
    "step": {
      "init": {
        "description": "Reconfigure QCells inverter.",
        "data": {
          "host": "[%key:common::config_flow::data::host%]",
          "password": "[%key:common::config_flow::data::password%]"
        }
      }
    },
    "error": {
      "cannot_connect": "[%key:common::config_flow::error::cannot_connect%]",
      "invalid_auth": "[%key:common::config_flow::error::invalid_auth%]",
      "unknown": "[%key:common::config_flow::error::unknown%]"
    }
  }
}
